{% set name = "pytools" %}
{% set version = "2024.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cccc184a10af56dabab3077af82ab0cf7a5b06625313cae0b2f06a3c4b126001

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - siphash24 >=1.6
    - python >=3.8
    - platformdirs >=2.2
    - typing_extensions >=4.0

test:
  requires:
    - pytest
    - pip
    - numpy >=1.6.0
  imports:
    - pytools
  commands:
    - pip check
    - python -m pytest --pyargs pytools

about:
  home: https://pypi.python.org/pypi/pytools
  license: MIT
  license_file: LICENSE
  summary: A collection of tools for Python

  description: |
    Pytools is a big bag of things that are "missing" from the Python standard
    library. This is mainly a dependency of my other software packages, and is
    probably of little interest to you unless you use those. If you're curious
    nonetheless, here's what's on offer.

  dev_url: https://github.com/inducer/pytools
  doc_url: https://documen.tician.de/pytools

extra:
  recipe-maintainers:
    - inducer
    - ocefpaf
    - matthiasdiener
